Improvement: add debug info because device not listed under /dev

diff --git a/aesd-char-driver/aesdchar_load b/aesd-char-driver/aesdchar_load
--- a/aesd-char-driver/aesdchar_load
+++ b/aesd-char-driver/aesdchar_load
@@ -5,6 +5,7 @@ mode="664"
 cd `dirname $0`
 set -e
 # Group: since distributions do it differently, look for wheel or use staff
+# https://en.wikipedia.org/wiki/Wheel_(computing)
 if grep -q '^staff:' /etc/group; then
     group="staff"
 else
@@ -21,5 +22,11 @@ fi
 major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
 rm -f /dev/${device}
 mknod /dev/${device} c $major 0
+if [ $? -eq 0 ]; then
+    echo "Device node /dev/${device} created successfully."
+else
+    echo "Failed to create device node /dev/${device}."
+    exit 1
+fi
 chgrp $group /dev/${device}
 chmod $mode  /dev/${device}
